POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
    "password": "test",
    "email": "test2@test.com",
    "name": "Test User 2",
    "roles": "user"
}

###
POST http://178.251.45.13:1080/api/signup/
Content-Type: application/json

{
    "password": "test",
    "email": "test3@test.com",
    "name": "Test User 3",
    "roles": "admin"
}

###
POST http://178.251.45.13:1080/api/auth/login
Content-Type: application/json

{
    "password": "test",
    "email": "test@test.com"

}

###
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{"email": "test@test.com", 
 "password": "test"
}

###


POST http://127.0.0.1:8000/api/clients/
{
    "name": ""
}


###
POST http://127.0.0.1:8000/api/projects/
Content-Type: application/json

{
    "name": "",
    "start_date": null,
    "due_date": null,
    "client": null,
    "prerequisites": [], 
    "assignee": []
}

###

POST http://127.0.0.1:8000/api/tasks/
{
    "description": "",
    "start_date": null,
    "due_date": null,
    "project": null,
    "assignee": null,
    "prerequisites": []
}