POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
    "password": "test",
    "email": "test10@test.com",
    "name": "Test User 10",
    "roles":["user", "admin"]
}

###
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{"username": "test", 
 "password": "test"
}

###


POST http://127.0.0.1:8000/api/clients/
{
    "name": ""
}


###
POST http://127.0.0.1:8000/api/projects/
Content-Type: application/json

{
    "name": "",
    "start_date": null,
    "due_date": null,
    "client": null,
    "prerequisites": [], 
    "assignee": []
}

###

POST http://127.0.0.1:8000/api/tasks/
{
    "description": "",
    "start_date": null,
    "due_date": null,
    "project": null,
    "assignee": null,
    "prerequisites": []
}