# Generated by Django 5.0.6 on 2024-06-28 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("waiting", "Waiting")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projectmanager.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("finished", "Finished")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "is_billable",
                    models.CharField(
                        choices=[
                            ("billable", "Billable"),
                            ("non-billable", "Non-billable"),
                        ],
                        default="billable",
                        max_length=12,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projectmanager.task",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
