# Generated by Django 5.0.6 on 2024-06-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="start_time",
            field=models.TimeField(auto_now_add=True),
        ),
    ]
