# Generated by Django 5.0.6 on 2024-08-26 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="start_date",
            new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="created_at",
            new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="update",
            old_name="created_at",
            new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="update",
            old_name="new_value",
            new_name="newValue",
        ),
        migrations.RenameField(
            model_name="update",
            old_name="old_value",
            new_name="oldValue",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="update",
            name="created_by",
        ),
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_project",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
