# Generated by Django 5.0.6 on 2024-08-26 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0002_rename_start_date_issue_createdat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="sub_project",
        ),
    ]
