# Generated by Django 5.0.6 on 2024-06-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0002_alter_tasklog_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="end_time",
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="projectmanager.client",
            ),
        ),
    ]
