# Generated by Django 5.0.6 on 2024-07-05 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0003_project_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="asignee",
            new_name="assignee",
        ),
    ]
