# Generated by Django 5.0.6 on 2024-08-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0003_remove_project_sub_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[("Low", "low"), ("Medium", "medium"), ("High", "high")],
                default="low",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "accepted"),
                    ("Waiting", "waiting"),
                    ("Resolved", "resolved"),
                ],
                default="waiting",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="type",
            field=models.CharField(
                choices=[
                    ("Question", "question"),
                    ("Incident", "incident"),
                    ("Problem", "problem"),
                ],
                default="question",
                max_length=50,
            ),
        ),
    ]
