# Generated by Django 5.0.6 on 2024-06-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projectmanager",
            "0003_client_alter_task_start_date_alter_tasklog_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="projectmanager.client"
            ),
        ),
    ]
