# Generated by Django 5.0.6 on 2024-08-26 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0004_ticket_priority_ticket_status_ticket_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="assignee",
        ),
        migrations.AddField(
            model_name="issue",
            name="assignee",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
