# Generated by Django 5.0.6 on 2024-08-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0005_remove_issue_assignee_issue_assignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projectmanager.comment",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="projectmanager.project"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="update",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projectmanager.update",
            ),
        ),
    ]
