# Generated by Django 5.0.6 on 2024-06-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0005_tasklog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="is_read_only",
            field=models.BooleanField(default=False),
        ),
    ]
