# Generated by Django 5.0.6 on 2024-07-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0006_remove_team_players_delete_player_delete_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, null=True, to="projectmanager.project"
            ),
        ),
    ]
