# Generated by Django 5.0.6 on 2024-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0006_tasklog_is_read_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="total_time",
            field=models.FloatField(default=0.0),
        ),
    ]
