# Generated by Django 5.0.6 on 2024-08-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0006_alter_issue_comment_alter_issue_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projectmanager.comment",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="projectmanager.project",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="update",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projectmanager.update",
            ),
        ),
    ]
