# Generated by Django 5.0.6 on 2024-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0007_alter_project_prerequisites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="prerequisites",
            field=models.ManyToManyField(blank=True, to="projectmanager.project"),
        ),
    ]
