# Generated by Django 5.0.6 on 2024-08-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0008_alter_issue_project_alter_issue_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projectmanager.comment",
            ),
        ),
    ]
