# Generated by Django 5.0.6 on 2024-06-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0008_alter_tasklog_total_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="total_time",
            field=models.FloatField(default=0.0),
        ),
    ]
