# Generated by Django 5.0.6 on 2024-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0008_alter_project_prerequisites"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("Medium", "medium"), ("High", "high")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
