# Generated by Django 5.0.6 on 2024-08-27 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0009_alter_issue_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
                ("dueDate", models.DateField()),
                ("startDate", models.DateField()),
                ("updatedAt", models.DateField(auto_now=True)),
                ("createdAt", models.DateField(auto_now=True)),
                ("assignee", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "createdBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectmanager.issue",
                    ),
                ),
                (
                    "subproject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projectmanager.project",
                    ),
                ),
            ],
        ),
    ]
