# Generated by Django 5.0.6 on 2024-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0009_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("waiting", "Waiting"),
                    ("canceled", "Canceled"),
                    ("finished", "Finished"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
