# Generated by Django 5.0.6 on 2024-06-28 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0010_remove_tasklog_task_remove_tasklog_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="projectmanager.task",
            ),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasklogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
