# Generated by Django 5.0.6 on 2024-06-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0011_tasklog_task_tasklog_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklog",
            name="is_read_only",
        ),
        migrations.AddField(
            model_name="tasklog",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
