# Generated by Django 5.0.6 on 2024-08-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0011_subproject_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="subproject",
            name="createdAt",
            field=models.DateField(auto_now=True),
        ),
    ]
