# Generated by Django 5.0.6 on 2024-07-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0012_rename_tasklog_log_issue_alter_log_task_delete_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="feature",
            field=models.CharField(
                choices=[("task", "Task"), ("bug", "Bug"), ("feature", "Feature")],
                default="task",
                max_length=10,
            ),
        ),
    ]
