# Generated by Django 5.0.6 on 2024-06-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0012_remove_tasklog_is_read_only_tasklog_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="read_only",
            field=models.BooleanField(default=False),
        ),
    ]
