# Generated by Django 5.0.6 on 2024-07-26 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0013_issue_feature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="prerequisites",
        ),
    ]
