# Generated by Django 5.0.6 on 2024-06-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0013_tasklog_read_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="terminate",
            field=models.BooleanField(default=False),
        ),
    ]
