# Generated by Django 5.0.6 on 2024-07-26 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0014_remove_issue_prerequisites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="prerequisites",
        ),
    ]
