# Generated by Django 5.0.6 on 2024-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0014_tasklog_terminate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
