# Generated by Django 5.0.6 on 2024-06-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0015_alter_task_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
