# Generated by Django 5.0.6 on 2024-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0016_alter_task_due_date_alter_task_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="slug",
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(),
        ),
    ]
