# Generated by Django 5.0.6 on 2024-07-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projectmanager",
            "0016_user_alter_checkin_user_alter_issue_assignee_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                choices=[("Admin", "admin"), ("User", "user"), ("Guest", "guest")],
                default="User",
                max_length=5,
            ),
        ),
    ]
