# Generated by Django 5.0.6 on 2024-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0017_remove_task_slug_alter_task_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="prerequisites",
            field=models.ManyToManyField(to="projectmanager.task"),
        ),
    ]
