# Generated by Django 5.0.6 on 2024-07-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectmanager", "0018_task_prerequisites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, null=True, to="projectmanager.task"
            ),
        ),
    ]
