# Generated by Django 5.0.6 on 2024-08-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0020_alter_issue_start_date_comment_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
