# Generated by Django 5.0.6 on 2024-08-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0021_remove_project_client_remove_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
