# Generated by Django 5.0.6 on 2024-08-08 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0026_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.subproject'),
        ),
    ]
