# Generated by Django 5.0.6 on 2024-08-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0027_project_sub_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comment',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.comment'),
        ),
        migrations.AddField(
            model_name='issue',
            name='update',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.update'),
        ),
    ]
